### ISSUE TITLE
🙃 Add a function that will replace each letter with an emoji 

### ISSUE THREAD

**Issue by LucyMcGowan** [hadley/emo#22]
_An ode to my favorite princess_. 
Carrie Fisher often wrote in emojis by replacing each letter with an emoji that resembled it. For example,

```r
emo::ji_fisher("without you I would just be a weird chick in a hat")
#> 〰ℹ✝️♓️🅾️⛎✝️ ✌🏻️🅾️⛎ ℹ 〰🅾️⛎🕒d 🌶⛎💲✝️ 🅱️📧🅰️ 〰ℹ📧®d ©♓️ℹ©🎋 ℹ️♑️ 🅰️ ♓️🅰️✝️
```
ref: [tweet](https://twitter.com/carrieffisher/status/804114429071630336)
```r
emo::ji_fisher("Im supposed to tell you to buy my book, but Im not really like that!")
#> ℹ♏️ 💲⛎🅿️🅿️🅾️💲📧d ✝️🅾️ ✝️📧🕒🕒 ✌🏻️🅾️⛎ ✝️🅾️ 🅱️⛎✌🏻️ ♏️✌🏻️ 🅱️🅾️🅾️🎋, 🅱️⛎✝️ ℹ♏️ ♑️🅾️✝️ ®📧🅰️🕒🕒✌🏻️ 🕒ℹ🎋📧 ✝️♓️🅰️✝️❕
```
ref: [tweet](https://twitter.com/carrieffisher/status/803307648057679872)

```r
emo::ji_fisher("I love the new rstudio")
#> ℹ️   👍❤️✌️📧  🌴♓️📧  🆕   ®️⚡️🌴⛎↩️ℹ️⭕️
```

A bit similar to #5, but different in that rather than replace full words, it would just replace letters.

**Comment by romainfrancois** [comment]
That'd be cool. 
This would allow me to participate to slack://ropensci#allemoji

Are all those emojis ? or do we need to also poke into other unicode planes, e.g. 

```
> filter( uni::code, str_detect(description, "registered") )
# A tibble: 1 x 7
     id   rune                                   description              block countries languages  type
  <int>  <chr>                                         <chr>              <chr>     <chr>     <chr> <chr>
1   174 U+00AE  Registered Sign : registered trade mark sign latin-1-supplement      <NA>      <NA>  <NA>
```

**Comment by LucyMcGowan** [comment]
Some of Carrie's weren't emojis, but I think as a first pass we can just use emojis? I have at least a 1:1 alphabet to emoji mapping I generally use I can write up.

**Comment by romainfrancois** [comment]
cool. It does not necessarily need to be 1:1 some letters (o) might have many proxy emojis .. `ji_fisher` could randomly select one

**Comment by LucyMcGowan** [comment]
Here is a [start of the mapping](https://github.com/lucymcgowan/emoji_fisher) 👸

**Comment by romainfrancois** [comment]
Would you prepare a PR for emo ?

Cple of things though: 
- please use purrr instead of sapply
- return a string w class "emoji" instead of directly cat it, print.emoji will cat it. It makes the function

**Comment by LucyMcGowan** [comment]
Yep! How would you like the data saved? Right now I create a tibble, turn it into a list, and then export that.

**Comment by romainfrancois** [comment]
That sounds fine
