### ISSUE TITLE
Submodules means that install_github doesn't work

### ISSUE THREAD

**Issue by hadley** [hadley/emo#36]
And hence adv-r is now failing to build 😢

**Comment by hadley** [comment]
Hmmm, the submodules are only in `data-raw` which shouldn't cause problems. 

I think maybe the data source has changed?  The main problem is that `emo::ji("dark_sunglasses")` no longer works for me.

**Comment by romainfrancois** [comment]
I only use the submodules for data-raw. 

This was only supposed to use _more_ data sources. I’ll have a look at why this alias no longer works.

**Comment by romainfrancois** [comment]
`dark_sunglasses` are back

```
> emo::ji("dark_sunglasses")
🕶 
```

should I remove the submodules ? We only really need this when we update the data ? @hadley

**Comment by romainfrancois** [comment]
This was because the dark sunglasses emoji is not "fully qualified" so was filtered out in the data. 
Side effect is now I need to find a way to update the regex to cover non fully qualified emojis. #41

**Comment by hadley** [comment]
Submodules are fine for the raw data
